version: "3"
services:
  db:
    image: mysql
    container_name: thelibrary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: thelibrary.secret
    volumes:
      - ./Docker/db:/var/lib/mysql
      - ./Docker/conf/mysql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  app:
    build: .
    container_name: thelibrary-app
    command: sh -c "sh ./Docker/init_scripts/wait_db_container_then_start_django.sh"
    volumes:
      - .:/home/thelibrary/app
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: thelibrary-nginx
    volumes:
      - ./Docker/conf/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - app